import { useEffect, useState } from "react";
import { api, type Status } from "./api";
import { ErrorBox, Loading, ModeBadge } from "./components/Common";
import { useUrlState } from "./url";
import Explore from "./views/Explore";
import PairView from "./views/PairView";
import Playback from "./views/Playback";
import BacktestView from "./views/BacktestView";
import Method from "./views/Method";

const NAV: [string, string][] = [["explore", "Explore"], ["pair", "Pair detail"], ["playback", "Playback"],
  ["backtest", "Backtest"], ["method", "Method & data"]];

export default function App() {
  const [params, setParams] = useUrlState();
  const [status, setStatus] = useState<Status | null>(null);
  const [err, setErr] = useState<string | null>(null);
  useEffect(() => { api.status().then(setStatus).catch((e) => setErr(String(e.message ?? e))); }, []);
  const view = params.get("view") ?? "explore";
  const first = status?.candidate_pairs[0];
  const a = params.get("a") ?? first?.a ?? "";
  const b = params.get("b") ?? first?.b ?? "";

  const go = (v: string) => {
    const keep: Record<string, string | null> = { view: v };
    if (v === "explore" || v === "method") { keep.a = null; keep.b = null; keep.asof = null; }
    else { keep.a = a; keep.b = b; }
    keep.reveal = null;
    setParams(keep);
  };

  return (
    <div className="app">
      <header className="topbar">
        <a className="brand" href="?" onClick={(e) => { e.preventDefault(); go("explore"); }}>
          <svg viewBox="0 0 32 32" width="26" height="26" aria-hidden="true">
            <path d="M3 22 Q10 6 16 16 T29 10" stroke="#2a78d6" strokeWidth="3" fill="none" />
            <path d="M3 12 Q10 26 16 16 T29 22" stroke="#eb6834" strokeWidth="3" fill="none" />
          </svg>
          <span>Pairs Divergence Explorer</span>
        </a>
        <nav className="nav" aria-label="Views">
          {NAV.map(([k, label]) => (
            <button key={k} className={view === k ? "active" : ""} aria-current={view === k ? "page" : undefined}
              onClick={() => go(k)} data-testid={`nav-${k}`}>{label}</button>
          ))}
        </nav>
        {status && <ModeBadge mode={status.mode} />}
      </header>
      {status && (
        <div className={`source-strip mode-${status.mode}`} data-testid="source-strip">
          {status.mode === "SYNTHETIC_DEMO"
            ? <><strong>Synthetic demonstration.</strong> All prices are generated by the canonical seed-{String(status.manifest.seed)} generator; no market finding is asserted. Symbols are fictional.</>
            : <><strong>{status.mode.replace(/_/g, " ")}.</strong> Source {String(status.manifest.source ?? status.source)}.</>}
          <span className="strip-meta"> Data {status.first_date} → {status.last_date} · {status.sessions} sessions · calendar: {status.calendar === "weekdays_only_not_nse_calendar" ? "weekday simulation (not the NSE holiday calendar)" : status.calendar.replace(/_/g, " ")}
            {status.display_policy.observation_cutoff ? ` · age-gated to ${status.display_policy.observation_cutoff}` : ""}</span>
        </div>
      )}
      <main className="main">
        {err && <ErrorBox error={err} />}
        {!status && !err && <Loading what="dataset status" />}
        {status && view === "explore" && <Explore status={status} setParams={setParams} />}
        {status && view === "pair" && <PairView status={status} a={a} b={b} asOf={params.get("asof")} setParams={setParams} />}
        {status && view === "playback" && <Playback status={status} a={a} b={b} asOf={params.get("asof")}
          reveal={params.get("reveal") === "1"} setParams={setParams} />}
        {status && view === "backtest" && <BacktestView status={status} a={a} b={b} params={params} setParams={setParams} />}
        {status && view === "method" && <Method status={status} />}
      </main>
      <footer className="footer">
        Hypothetical, historical research tool. Not investment advice; no buy/sell recommendations. z-scores are distances in
        historical spread standard deviations, not probabilities of profit. Local/private preview.
      </footer>
    </div>
  );
}
